CREATE TABLE IF NOT EXISTS `death_register` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `death_register_no` varchar(50) NOT NULL,
  `ipd_no` int(11) NOT NULL,
  `opd_no` int(11) DEFAULT NULL,
  `uhid` varchar(100) DEFAULT NULL,
  `patient_name` varchar(255) DEFAULT NULL,
  `age` varchar(50) DEFAULT NULL,
  `gender` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `mobile` varchar(50) DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `ward_no` varchar(50) DEFAULT NULL,
  `bed_no` varchar(50) DEFAULT NULL,
  `admission_date` date DEFAULT NULL,
  `admission_time` varchar(20) DEFAULT NULL,
  `death_date` date NOT NULL,
  `death_time` varchar(20) NOT NULL,
  `treating_doctor` varchar(255) DEFAULT NULL,
  `certifying_doctor` varchar(255) NOT NULL,
  `diagnosis_at_admission` text DEFAULT NULL,
  `final_diagnosis` text DEFAULT NULL,
  `immediate_cause` text NOT NULL,
  `antecedent_cause` text DEFAULT NULL,
  `underlying_cause` text DEFAULT NULL,
  `other_significant_conditions` text DEFAULT NULL,
  `mccd_form4_issued` tinyint(1) NOT NULL DEFAULT 0,
  `mlc_case` tinyint(1) NOT NULL DEFAULT 0,
  `police_informed` tinyint(1) NOT NULL DEFAULT 0,
  `crs_registration_no` varchar(100) DEFAULT NULL,
  `body_handed_over_to` varchar(255) DEFAULT NULL,
  `informant_name` varchar(255) DEFAULT NULL,
  `informant_relation` varchar(100) DEFAULT NULL,
  `informant_mobile` varchar(50) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `entered_by` int(11) DEFAULT NULL,
  `verified_by` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_death_register_ipd` (`ipd_no`),
  UNIQUE KEY `uniq_death_register_no` (`death_register_no`),
  KEY `idx_death_register_death_date` (`death_date`),
  KEY `idx_death_register_department` (`department`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
