INSERT INTO `diagnosis` (`diagnosis_name`, `diagnosis_desc`, `InActive`)
SELECT seed.diagnosis_name, seed.diagnosis_name, 0
FROM (
  SELECT 'ACCIDENT' AS diagnosis_name
  UNION SELECT 'ALLERGIC SKIN RASHES'
  UNION SELECT 'BACK ACHE'
  UNION SELECT 'BURN'
  UNION SELECT 'CRAMPS'
  UNION SELECT 'CUT WOUND'
  UNION SELECT 'DERMATITIS'
  UNION SELECT 'EPISTAXIS'
  UNION SELECT 'EYE LID PAIN'
  UNION SELECT 'GENRAL WEAKNESS'
  UNION SELECT 'HEAD ACHE & COLD'
  UNION SELECT 'INJURY'
  UNION SELECT 'JOINT PAIN'
  UNION SELECT 'KNEE JOINT'
  UNION SELECT 'MOUTH ULCER'
  UNION SELECT 'NECK PAIN'
  UNION SELECT 'SCORPION BITE'
  UNION SELECT 'SEVERE ABDOMINAL PAIN'
  UNION SELECT 'SKIN RASHES'
  UNION SELECT 'STOMATITIS'
  UNION SELECT 'STYE'
  UNION SELECT 'THROAT PAIN'
  UNION SELECT 'VOMITING'
  UNION SELECT 'WIDAL FEVER'
  UNION SELECT 'WOUND'
) seed
WHERE NOT EXISTS (
  SELECT 1
  FROM `diagnosis` existing
  WHERE UPPER(TRIM(existing.`diagnosis_name`)) = seed.diagnosis_name
);
